language: c
sudo: false
cache:
   directories:
   - ~/arduino_ide
   - ~/.arduino15/packages/
git:
   depth: false
   quiet: true
env:
   global:
   - PRETTYNAME="LightweightServo Arduino Library"
   - INSTALL_PLATFORMS="avr"
#--verbose --verbose-build --version
   - ARDUINO_SWITCHES="--verbose-build"
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/ArminJo/travis-ci-arduino/master/install.sh)
script:
- build_platform uno
notifications:
   email:
      recipients:
      - armin.arduino@gmail.com
      on_success: always
      on_failure: always
